### ISSUE TITLE
Cycles are no longer being reported on mac

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#18]
After commit c52432c3261c1c5731ca998864397c600b544b26, cycles are not reported on mac os x. I see this in time-osx.c:

```
    tr->rdtsc = 0;
```

Older code used this for mac (cycles.c):

```
#if x86_64_HOST_ARCH || i386_HOST_ARCH

StgWord64 gauge_rdtsc(void)
{
  StgWord32 hi, lo;
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  return ((StgWord64) lo) | (((StgWord64) hi)<<32);
}
```

@vincenthz is this deliberate or pending?

**Comment by vincenthz** [comment]
I noticed that the rdtsc primitive was not ideal (using 32 bit rdtsc), which is why I hardcoded to 0 on mac/windows. I should have open an issue to keep track of it.

**Comment by harendra-kumar** [comment]
Isn't it a 64-bit counter returning 32-bits in EAX and 32-bits in EDX? We are then combining those two values to return a 64-bit value. Is there something wrong with that? Is there an alternative to it on os x? Do we have perf counter support available? I think BSD has had perf counter support for quite some time now, not sure about os x.

**Comment by vincenthz** [comment]
there's an rdtsc instruction (and rdtscp which I think we should be using) that fill 64 bits directly on 64 bits.

**Comment by harendra-kumar** [comment]
Sounds good then.

**Comment by vincenthz** [comment]
fixed by #22

**Comment by harendra-kumar** [comment]
@vincenthz this issue is still not fixed. Cycles are still not being reported on mac, they are always 0. Also, now utime and stime are also always reported as 0 on mac, they seem to be fine on Linux. Maybe there is some difference in the timeval structure on mac vs Linux?
